---
title: "terms"
output: html_document
---

## Terms of Use

The **BURDEN OF ASTHMA IN THE US (the “ASTHMA VISUALIZATION”)** is a web-based tool to provide data visualizations of the burden of asthma and associated costs of asthma in the United States. The **Asthma Visualization Tool** was developed by Ainsleigh Hill, Mohsen Yaghoubi, Amin Adibi, Dr. Mohsen Sadatsafavi, Abdollah Safari, and J Mark FitzGerald at UBC.
You (the **End User**) are granted access to use the **Asthma Visualization Tool** only on the condition that the **End User** agrees to the terms of use set forth below.  

The **End User** acknowledges that the **Asthma Visualization Tool** resource developed and conceived by UBC, including any and all improvements, variations, updates, upgrades, modifications, enhancements or derivative works (the **Asthma Visualization Tool**) is owned by UBC and that UBC specifically retains the right to grant licenses of the **Asthma Visualization Tool** to other persons.   
The **Asthma Visualization Tool** resource is provided to the End User for research, educational and non-commercial purposes only.

### Clinical Use Advisory

The **Asthma Visualization Tool** is an experimental technology and has not been tested or approved for use in connection with any human clinical use. The **Asthma Visualization Tool** and any content or other information contained in the **Asthma Visualization Tool**, accessed through or provided by the **Asthma Visualization Tool** is for informational purposes only and is in no way intended to serve as a substitute for professional medical advice or to provide any medical or clinical judgment or individualized patient care. The **End User** should seek professional medical advice in evaluating the information provided within the **Asthma Visualization Tool**. UBC also recommends that the **End User** consult with medical professionals for health evaluation, diagnostic or treatment decisions.

### Disclaimer of Warranty

The **End User** acknowledges and agrees that the **Asthma Visualization Tool** is being provided “as is” and that to the extent that the **Asthma Visualization Tool** or any such updates, upgrades or enhancements to the **Asthma Visualization Tool** are provided by or on behalf of UBC to the **End User**, the following disclaimers of warranty and limitations of liability shall apply in connection therewith. UBC does *not*:

(a) warrant or guarantee that any content or other information contained in or provided by the **Asthma Visualization Tool** is accurate or error free;
(b) undertake to provide the **End User** with any maintenance or support services related to the LUNG FUNCTION PREDICTOR, including, without limitation, any updates, upgrades or enhancements thereto; or
(c) assume any obligation to obtain and update any content or information contained in or accessed through the **Asthma Visualization Tool**

The **End User** further acknowledges and agrees that:

(i) the **Asthma Visualization Tool** is intended for use only as a research and educational tool;  
(ii) it is the sole responsibility of the **End User** to determine his/her application and use of the **Asthma Visualization Tool**;
(iii) the **Asthma Visualization Tool** is not intended as a replacement for professional medical advice or a health professional’s medical and clinical judgment (iv) UBC will not be responsible for any errors, misstatements, inaccuracies, or omissions in the **Asthma Visualization Tool**;
(v) UBC will not be responsible for any delays or interruptions in the use of the **Asthma Visualization Tool**;
(vi) UBC has no control of or responsibility for the **End User**'s use of the **Asthma Visualization Tool** and has no knowledge of the specific or unique circumstances under which the **Asthma Visualization Tool** or information provided by the **Asthma Visualization Tool** may be used by the **End User**; and
(vii) the **End User** assumes sole responsibility for any and all use of the **Asthma Visualization Tool** including any use of any content or other information contained in or accessed through the **Asthma Visualization Tool**. Furthermore, the End User acknowledges that the **Asthma Visualization Tool** is being provided without representation or warranty of any kind. By way of example and not limitation, UBC makes no representations or warranties of commercial utility, title, merchantability, or fitness for a particular purpose or any other warranty, express or implied. UBC makes no representation that the use of the **Asthma Visualization Tool** will not infringe any patent, copyright, trademark, or other property or proprietary rights.

### Limitation of Liability
UBC will not be liable to the **End User** or any other person or entity (including but not limited to persons treated by the **End User** or on behalf of the **End User**) for any liability, loss or damages caused or alleged to have been caused, either directly or indirectly, by the use of **Asthma Visualization Tool**.  Without limitation, in no event will UBC be liable for any tort, personal injury, medical malpractice, misdiagnosis, death, product liability, loss of profit or data, or for special, indirect, consequential, incidental or punitive damages, however caused and regardless of the theory of liability, arising out of or related to the use of or inability to use the **Asthma Visualization Tool**, even if UBC has been advised of the possibility of such loss or damages.

### Indemnity

To the fullest extent permitted by law, the **End User** agrees to indemnify, defend, and hold harmless UBC and its Board of Governors, Officers, Directors, Faculty, Students, Employees, and Agents (collectively the **Indemnitees**) from and against all claims, actions liabilities, losses, expenses, damages and costs (including, without limitation, reasonable legal fees) (**Claims**) that may at any time be incurred by any of them by reason of any claims, suits or proceedings arising from
(a) the **End User**'s use of the **Asthma Visualization Tool** or by any other party authorized by the **End User**, and
(b) any breach by the **End User** of any representation, condition or term of this license agreement.
Without limitation, this indemnity shall include any claims brought by third parties against the indemnitees in tort, or for personal injury, medical malpractice, misdiagnosis, death, product liability, loss of profit or data, or for special, indirect, consequential, incidental, or punitive damages, however cause and regardless or the theory of liability, arising out of or related to the **End User**'s use of, or inability to use, the **Asthma Visualization Tool**.

### Governing Law
This Agreement will be governed and interpreted according to the laws of British Columbia, Canada.  The Licensee agrees that by accepting the terms of this Agreement and using the **Asthma Visualization Tool**, the Licensee has attorned to the exclusive jurisdiction of the courts of competent authority in the Province of British Columbia.
